server:
  port: 8081
  servlet:
    context-path: /api
---
spring:
  config:
    activate:
      on-profile: local, default
  datasource:
    url: jdbc:h2:~/test
    username: carRenter
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:mysql://localhost/CarRental
    username: carRenter
    password: KwesIN%%er!
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
